# Generated by Django 5.1.6 on 2025-02-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_transaction_user_transaction_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
    ]
